name: PDF

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths: 
      - '*.tex'
      - '*.sty'
      - '*.tikz'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 all: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from git
        uses: actions/checkout@v2
      - name: Install Basics 
        run:  sudo apt install -y git make 
      - name: Install Languages 
        run:  sudo apt-get install -y fp-compiler ocaml 
      - name: Install XeLaTeX
        run:  sudo apt-get install -y texlive-xetex latexmk
      - name: Install TeXLive Extra
        run:  sudo apt-get install -y texlive-extra-utils texlive-lang-arabic texlive-science-doc 
      - name: Install Fonts 
        run:  sudo apt-get install  -y texlive-fonts-extra texlive-science fonts-lmodern 
      - name: Setup fonts 
        run: echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections && sudo apt-get install ttf-mscorefonts-installer && mkdir -p ~/.fonts ; cp ./fonts/* ~/.fonts/ && fc-cache -f

      - name: 00.pdf 
        run: latexmk -f -file-line-error -halt-on-error -shell-escape 00
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          path: ./00.pdf
          if-no-files-found: error

      - name: mini-lisp.pdf
        run: latexmk -f -file-line-error -halt-on-error -shell-escape mini-lisp || true
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          path: ./mini-lisp.pdf
          if-no-files-found: error
            
      - name: evaluation.pdf
        run: latexmk -f -file-line-error -halt-on-error -shell-escape evaluation || true
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          path: ./evaluation.pdf
          if-no-files-found: error
                         
      - name: background.pdf
        run: latexmk -f -file-line-error -halt-on-error -shell-escape background || true
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          path: ./background.pdf
          if-no-files-found: error
                         
      - name: techniques.pdf
        run: latexmk -f -file-line-error -halt-on-error -shell-escape techniques || true
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          path: ./techniques.pdf
          if-no-files-found: error

      - name: recursion-games.pdf 
        run: latexmk -f -file-line-error -halt-on-error -shell-escape recursion-games|| true
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          path: ./recursion-games.pdf
          if-no-files-found: error

      - name: lexical.pdf 
        run: latexmk -f -file-line-error -halt-on-error -shell-escape lexical || true
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          path: ./lexical.pdf
          if-no-files-found: error

      - name: JVM.pdf 
        run: latexmk -f -file-line-error -halt-on-error -shell-escape JVM || true
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          path: ./JVM.pdf
          if-no-files-found: error


