name: PDF

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Basics 
        run:  sudo apt install -y git make 
      - name: Install Languages 
        run:  sudo apt install -y fp-compiler ocaml 
      - name: Install Latex
        run:  sudo apt install -y texlive-xetex texlive-extra-utils texlive-lang-arabic texlive-science-doc 
      - name: Install Fonts 
        run:  sudo apt install  -y texlive-fonts-extra texlive-science fonts-lmodern 
      - name: Setup fonts 
        run: echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections && sudo apt-get install ttf-mscorefonts-installer && mkdir -p ~/.fonts ; cp ./fonts/* ~/.fonts/ && fc-cache -f

  tex-00:
      needs: install
      steps:
        - name: Compile main book as one document
          run: xelatex -file-line-error -halt-on-error -shell-escape 00
          if: ${{ always() }}
          with:
            name: Pdf Book
            path: ./00.pdf
            if-no-files-found: error
        
        
  mini-lisp:
    needs: install
    steps:
      - name: Compile mini-lisp 
        run: xelatex -file-line-error -halt-on-error -shell-escape mini-lisp
        if: ${{ always() }}
        with:
          name: Mini-lisp.pdf
          path: ./mini-lisp.pdf
          if-no-files-found: error
