name: PDF

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  try: 
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Setup fonts 
        run: echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections && sudo apt-get install ttf-mscorefonts-installer && mkdir -p ~/.fonts ; cp ./fonts/* ~/.fonts/ && fc-cache -f
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: mini-lisp.tex 
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
      - uses: actions/upload-artifact@v2
        with:
          path: mini-lisp.pdf 

  install: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Basics 
        run:  sudo apt install -y git make 
      - name: Install Languages 
        run:  sudo apt-get install -y fp-compiler ocaml 
      - name: Install XeLaTeX
        run:  sudo apt-get install -y texlive-xetex
      - name: Install TeXLive Extra
        run:  sudo apt-get install -y texlive-extra-utils texlive-lang-arabic texlive-science-doc 
      - name: Install Fonts 
        run:  sudo apt-get install  -y texlive-fonts-extra texlive-science fonts-lmodern 
      - name: Setup fonts 
        run: echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections && sudo apt-get install ttf-mscorefonts-installer && mkdir -p ~/.fonts ; cp ./fonts/* ~/.fonts/ && fc-cache -f
      - name: Latex 
        run: xelatex -file-line-error -halt-on-error -shell-escape 00

  tex-00:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Compile main book as one document
        run: xelatex -file-line-error -halt-on-error -shell-escape 00
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          path: ./00.pdf
          if-no-files-found: error
      
      
  mini-lisp:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Compile mini-lisp 
        run: xelatex -file-line-error -halt-on-error -shell-escape mini-lisp
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          path: ./mini-lisp.pdf
          if-no-files-found: error
